export const CHURRAS_FETCH = 'CHURRAS_FETCH';
export const CHURRAS_FETCH_FAIL = 'CHURRAS_FETCH_FAIL';
export const CHURRAS_FETCH_SUCCESS = 'CHURRAS_FETCH_SUCCESS';
export const CHURRAS_ADD = 'CHURRAS_ADD';
export const CHURRAS_EDIT = 'CHURRAS_EDIT';
export const CHURRAS_DELETE = 'CHURRAS_DELETE';
